config/routes.rb
Rails.application.routes.draw do
  devise_for :members, :controllers => {registrations: 'registrations' }
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'posts#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :member

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_member!, except: [:index, :show]
  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_member.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_member.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


  private

  def sign_up_params
    params.require(:member).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:member).permit(:name, :email, :password, :password_confirmation, :current_password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Only Members</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="bg-gray-100">

      <div class="lg:h-10 w-full bg-blue-300 flex justify-between items-center text-lg">
          <ul class="flex">
            <li class="px-5 hover:text-blue-100"> <%= link_to "home", root_path %> </li>
          </ul>
          <ul class="flex">
          <% if member_signed_in? %>
            <li class="px-5 hover:text-blue-100"> <%= link_to "Log Out", destroy_member_session_path %> </li>
          <% else %>
            <li class="px-5 hover:text-blue-100"> <%= link_to "Sign Up", new_member_registration_path %> </li>
            <li class="px-5 hover:text-blue-100"> <%= link_to "Sign In", new_member_session_path %> </li>
          <% end %>
          </ul>
      </div>

      <p class="notice text-center text-red-500"><%= notice %></p>
      <p class="alert text-center text-red-500"><%= alert %></p>
    <%= yield %>


  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation ">
      <h2 class="text-red-400"><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul class="font-semibold text-red-500">
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="relative my-3">
    <%= form.label :title , class:"text-xl font-light" %> <br>
    <%= form.text_field :title, class:"bg-white w-full border border-blue-500 rounded-md focus:ring-2 focus:ring-blue-700 outline-none p-2" %>
  </div>

  <div class="my-3">
    <%= form.label :body, class:"text-xl font-light" %> <br>
    <%= form.text_area :body , class:"bg-white h-32 w-full border border-blue-500 rounded-md focus:ring-2 focus:ring-blue-700 outline-none p-2" %>
  </div>

  <div class="actions mb-5 text-white">
    <%= form.submit "Post", class:"bg-blue-500 py-1 px-3 rounded-lg shadow-md cursor-pointer" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="w-1/2 mt-10 mx-auto">
 <div class="w-1/4 mx-auto text-center">
  <%= link_to 'New Post', new_post_path, class: "px-4 py-2 bg-red-500 rounded-lg text-white" %>
 </div>

 <p id="notice"><%= notice %></p>

  <div class="flex flex-col gap-4 mt-5">
        <% @posts.each do |post| %>
        <div class="shadow-lg p-5 bg-white rounded-lg">
            <% if member_signed_in? %>
            <p class="text-lg font-semibold text-gray-800"> Author: <%= post.member.name %>  </p>
            <% else %>
            <p class="text-lg font-semibold text-gray-800"> Author: Anonymous</p>
            <% end %>
            <p class="font-semibold text-xl text-gray-700 mt-1" > <%= post.title%></p> 
            <p class="font-light mt-2 text-gray-700" > <%= post.body%> </p> 
        </div>
        <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="mx-auto w-1/4 mt-10 text-gray-800 py-4 px-5 rounded-lg">
<h1 class="text-2xl text-center mb-12 font-bold">Create New post</h1>
  <%= render 'form', post: @post %>

  <%= link_to 'Back', posts_path, class:"px-2 py-1 bg-red-500 text-white rounded-md" %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @post.title%>
  <%= @post.body%>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>